# Example docker-compose.yml with custom builds
# This is an example - uncomment sections as needed

version: "3.8"

services:
  postgres:
    image: postgres:17.5-bullseye
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak_server
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${DOMAIN}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    command:
      - start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_net

  nginx:
    # Option 1: Use pre-built image (current setup)
    image: nginx:latest
    # Option 2: Build from custom Dockerfile
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    container_name: keycloak_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak
    networks:
      - keycloak_net

  # Example: Add your custom application
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: my_app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - postgres
  #     - keycloak
  #   networks:
  #     - keycloak_net

  # Example: Add a Python API
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.python
  #   container_name: python_api
  #   restart: unless-stopped
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=production
  #     - DATABASE_URL=postgresql://keycloak:${POSTGRES_PASSWORD}@postgres:5432/keycloak
  #   depends_on:
  #     - postgres
  #   networks:
  #     - keycloak_net

volumes:
  postgres_data:
  certs:

networks:
  keycloak_net:
    driver: bridge
